version: "3"

services:
  app:
    container_name: auth_clean_architecture
    build: .
    volumes:
      - .:/go/src/auth_clean_architecture
    ports:
      - 4500:4500
  database:
    image: mongo
    container_name: mongo
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - 27017:27017
