version: "3"

services:
  app:
    container_name: auth_clean_architecture
    build: .
    volumes:
      - .:/go/src/auth_clean_architecture
    ports:
      - 4500:4500
      - 3000:3000
  database:
    image: mongo
    container_name: mongo
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
