version: "3"

services:
  app:
    container_name: auth_clean_architecture_app
    build: .
    volumes:
      - .:/go/src/auth_clean_architecture
    ports:
      - 4500:4500
      - 3000:3000
      - 3333:3333
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
